### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by LudovicPatho** [Anxium/progressive-enhancement#1]
Super bon travail Axel !

2 petites choses à rectifier 
Ta balise section à la ligne 83, mets lui un titre
Quand tu mets des images mets bien l'attribut alt pour l'accessibilité.

Mais si non c'est propre, bravo à toi. et continu comme ça

**Comment by Anxium** [comment]
Merci !

C'est réglé et vérifié avec le validator W3C.
